apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-elasticsearch-node1
  namespace: elk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
  volumeName: pv-elasticsearch-node1

